apiVersion: v1
kind: Service
metadata:
  name: tax-calculator-service
  labels:
    app: tax-calculator
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: tax-calculator
